name: Build with Maven

on:
  pull_request:
    branches:
      - main # запускать только для PR в main

jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Java version
        run: |
          echo "Using Java version:"
          java -version

      - name: Build, test and package with Maven
        run: mvn -B clean test package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/*.jar
  semgrep-sast:
    name: Semgrep SAST
    needs: build-job
    runs-on: ubuntu-latest

    # права, чтобы загружать отчёты сканирования кода
    permissions:
      security-events: write
      contents: read
      actions: read

    # запускаем в контейнере с semgrep CE
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep and generate SARIF report
        run: |
          # автоматический подбор правил по языку
          semgrep scan --config auto --sarif -o semgrep.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always() # загружаем отчёт даже если semgrep нашёл проблемы или упал
        with:
          sarif_file: semgrep.sarif

  dependency-check-sca:
    name: OWASP Dependency-Check (SCA)
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21" # или 17 — главное совпадает с проектом

      - name: Run Dependency-Check
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -Dformat=HTML \
            -DsuppressionFile=dependency-check-suppressions.xml \
            -Danalyzer.ossindex.enabled=false \
            -DfailBuildOnCVSS=11 \
            -DdataDirectory=.dependency-check

      - name: Upload Dependency-Check Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
